name: aicycle_buyme_plugin
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/Aicycle-Insurance/aicycle-buyme-plugin

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  #multi language
  easy_localization: ^3.0.1

  #state management
  flutter_bloc: ^8.0.1

  #dependency injection
  injectable: ^1.5.3
  get_it: ^7.2.0

  #serializable & data type
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  dartz: ^0.10.1
  copy_with_extension: ^4.0.2
  equatable: ^2.0.3
  rxdart: ^0.27.5
  collection: ^1.16.0

  #networking
  retrofit: ^3.3.1
  dio: ^4.0.6

  #image processing
  image: ^3.2.0

  #view
  lottie: ^1.4.3
  flutter_svg: ^1.1.0

  #other
  event_bus: ^2.0.0
  flutter_gen: ^4.3.0
  cached_network_image: ^3.2.1
  camerawesome: ^0.3.3
  image_picker: ^0.8.6
  path_provider: ^2.0.11
  path: ^1.8.2
  mime: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  freezed: ^2.0.3+1
  injectable_generator: ^1.5.3
  build_runner: ^2.1.11
  json_serializable: ^6.5.0
  retrofit_generator: ^4.2.0
  copy_with_extension_gen: ^4.0.2
  flutter_gen_runner: ^4.3.0

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true

  assets:
    enable: true
    package_parameter_enabled: false

  font:
    enable: true


flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
    - assets/svg/
    - assets/lotties/
    - assets/icon/